InsertTrainingEvent method #78
DSAV-Dodeka/backend pull request #79
Opened 2023-11-29 15:20 UTC by SenneDrent

Ik heb deze method nog niet getest, ik ben dit van plan te doen als ik ook de router heb geïmplementeerd.

2023-11-30 13:58 UTC, tiptenbrink commented on src/apiserver/data/api/trainings.py
> +    event_id will be created in the form of: "training[dd/mm/yyyy][category]"
isoformat is juist yyyy/mm/dd

2023-11-30 14:04 UTC, tiptenbrink requested changes

2023-11-30 14:04 UTC, tiptenbrink commented on src/apiserver/data/api/trainings.py
> +        subEventId = usp_hex(f'training{event_date.isoformat()}{subCategory}')
usp_hex is niet nodig omdat de categories waarschijnlijk hardcoded zullen zijn (we zullen nog wel een check toevoegen denk ik) en er dus geen rare karakters in zitten. Om dezelfde reden is de lengte check ook niet nodig lijkt me. Voor de rest top dus als je dat nog even snel aanpast kan ik mergen!

2023-11-30 14:04 UTC, tiptenbrink commented
Thanks! Zie mijn review comment, als dat klaar is zal ik mergen!

2023-12-07 17:20 UTC, SenneDrent commented on src/apiserver/data/api/trainings.py
> +    event_id will be created in the form of: "training[dd/mm/yyyy][category]"
gefixed met [deze commit]!(https://github.com/DSAV-Dodeka/backend/pull/79/commits/64379b100d78e34d084efccdac8453dcd66d13c9)

2023-12-07 17:20 UTC, SenneDrent commented on src/apiserver/data/api/trainings.py
> +        subEventId = usp_hex(f'training{event_date.isoformat()}{subCategory}')
gefixed met [deze commit]!(https://github.com/DSAV-Dodeka/backend/pull/79/commits/64379b100d78e34d084efccdac8453dcd66d13c9)

2023-12-07 17:21 UTC, SenneDrent commented
a shit, zat die dag de hele tijd voor SEM te strijden hahaha

2023-12-08 11:32 UTC, tiptenbrink approved these changes

2023-12-08 11:33 UTC, merged